### ISSUE TITLE
Trouble on "Building OCaml plugin" setup.sh step

### ISSUE THREAD

**Issue by darzu** [Ptival/PeaCoq#36]
When I run ./setup.sh, I've gotten everything to work up until the "Building OCaml plugin" then I get some sort of infinite loop. Attached is an example trace: [error.txt](https://github.com/Ptival/PeaCoq/files/251282/error.txt). I think it has to do with the Makefile.coq, specifically running "make clean" inside the plugin folder reproduces the issue for me.

I'm on OSX 10.11.4 (15E65).

**Comment by Ptival** [comment]
Hey Daryl,

Can you figure out where this `(cd ./Peacoq...)` line comes from? Is it in your generated `plugin/Makefile.coq`?

**Comment by darzu** [comment]
Hey Val,

Yeah, it's in [Makefile.coq.txt](https://github.com/Ptival/PeaCoq/files/251383/Makefile.coq.txt). Maybe I can regenerate this file somehow?

**Comment by darzu** [comment]
Also, I think this is unrelated but when I initially tried to run `setup.sh` I got this error:
`./setup.sh: line 19: NIX_LDFLAGS: unbound variable`. I got around this by commenting out lines 19-25 & 28. Maybe that mixed things up?

**Comment by Ptival** [comment]
That one was my fault, it should be fixed if you pull.

Could you erase everything in plugin/, then checkout the files that are
versioned, and rerun setup?

If it fails, send me the contents of your Makefile.coq, it looks like it is
being dumb. :(

**Comment by darzu** [comment]
I rm'ed my plugin/ folder and I'm still seeing the same thing. Here's my new
[Makefile.coq.txt](https://github.com/Ptival/PeaCoq/files/251440/Makefile.coq.txt).

Also, I now get this error `./setup.sh: line 19: [: -v: unary operator expected` but setup.sh ignores it and continues.

**Comment by darzu** [comment]
Julie is also having the exact same issue on her Mac. @deGravity however seems to have gotten in working on Arch Linux. Any thoughts on how to proceed, @Ptival? We're thinking about working off of an older commit because we're all able to get PeaCoq from the 505 timeframe working.

**Comment by Ptival** [comment]
What happens if you just remove the make clean part of the setup.sh?

It seems like it's giving you trouble and it's really not necessary, just
here to make sure the plugin gets rebuilt because I don't really track its
changes well.
- Valentin

**Comment by Ptival** [comment]
Huh, I did not see your `-v` error. I hate shell scripts... :(

If you know a portable way of testing whether a variable is set, let me know. I'll ask around if anyone has a Mac I could use to test this.

**Comment by darzu** [comment]
Thanks, commenting out lines 38-40 let the script finish. Now I can run the server however I'm not able to progress the type checker in any proof scripts. I'll try for a little while and then open another issue if I can't figure it out!

**Comment by Ptival** [comment]
PeaCoq components are now checked under linux and osx on Travis:

https://travis-ci.org/Ptival/PeaCoq/builds
https://travis-ci.org/Ptival/peacoq-plugin/builds
https://travis-ci.org/Ptival/peacoq-server/builds

This should prevent this kind of issue in general.
